blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Project support forum
    url: https://github.com/turboBasic/turboBasic/discussions
    about: |
      Please ask and answer questions here. In some cases, itâ€™s better to use discussions,
      especially when your topic doesnâ€™t fit into available issue templates.
